variables:
  CACHE_DIR: "$CI_PROJECT_DIR/build"
  CACHE_DIR2: "$CI_PROJECT_DIR/.gradle"
  
  ORIG_ARTIFACTS: "$CI_PROJECT_DIR/build/libs/NetherEssence-Forge-*.jar"
  ARTIFACTS: "$CI_PROJECT_DIR/NetherEssence-Forge-*.jar"

cache:
 paths:
 - $CACHE_DIR
 - $CACHE_DIR2
 key: "$CI_BUILD_REF_NAME"
 untracked: false

stages:
- deploy
- cleanup

before_script:
  - shopt -s extglob
    
deploy:
  stage: deploy
  script:
  - ./gradlew build uploadArchives curseforge uploadToModsIO -PcurseForgeApiKey=$curseForgeApiKey -PmodsioApiKey=$modsioApiKey
  - cp $ORIG_ARTIFACTS .
  when: manual
  artifacts:
    name: "NetherEssence-Forge-$(cat $CACHE_DIR/.version)"
    paths:
    - $ARTIFACTS

cleanup:
  stage: cleanup
  script:
  - ./gradlew clean
  - rm -vf $ARTIFACTS
  - mkdir -p $CACHE_DIR $CACHE_DIR2
  when: manual
